apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.busybox.image | quote }}
          imagePullPolicy: {{ .Values.busybox.imagePullPolicy }}
          command: ["sh", "-c", "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: migrate
          image: {{ include "url-shortener.image" (dict "registry" .Values.image.registry "repository" .Values.image.apiRepository "tag" .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "migrate.js"]
          envFrom:
            - configMapRef:
                name: url-shortener-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: postgres-password
  backoffLimit: 3
